include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    [lib/generated/**,lib/**.g.dart,lib/data/source/network/models/output/chatbot/**.dart]

  language:
    strict-raw-types: false
    strict-inference: false

  strong-mode:
    implicit-dynamic: true
    implicit-casts: true

  errors:
    invalid_assignment: info
    missing_return: error
    dead_code: info

linter:
  rules:
    public_member_api_docs: false
    omit_local_variable_types: true
    require_trailing_commas: false
    directives_ordering: false
    unawaited_futures: false
    sort_constructors_first: false
    no_default_cases: false
    type_annotate_public_apis: false
    prefer_if_elements_to_conditional_expressions: false
    always_declare_return_types: false
    sort_pub_dependencies: false
    prefer_interpolation_to_compose_strings: false
    lines_longer_than_80_chars: false
    avoid_multiple_declarations_per_line: false
    use_if_null_to_convert_nulls_to_bools: false
