// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2TbtmykWudSYO9JjFcKIyhR8sCPR7WGw',
    appId: '1:415407565980:web:fc73b4a573fc515e809159',
    messagingSenderId: '415407565980',
    projectId: 'one-one-learn',
    authDomain: 'one-one-learn.firebaseapp.com',
    storageBucket: 'one-one-learn.appspot.com',
    measurementId: 'G-N7NYXDYZ0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLvE6Elxk7Iw1d9yOO86mzxMqB6LFtlB4',
    appId: '1:415407565980:android:2082658ac5a44008809159',
    messagingSenderId: '415407565980',
    projectId: 'one-one-learn',
    storageBucket: 'one-one-learn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPRAc-3SHRb0TUE5rOT9J-kHD--xqVQo0',
    appId: '1:415407565980:ios:574b98425ea8d7f4809159',
    messagingSenderId: '415407565980',
    projectId: 'one-one-learn',
    storageBucket: 'one-one-learn.appspot.com',
    iosClientId: '415407565980-1r5ntulj3p5l0gut2edv3i70r517desf.apps.googleusercontent.com',
    iosBundleId: 'com.example.oneOneLearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPRAc-3SHRb0TUE5rOT9J-kHD--xqVQo0',
    appId: '1:415407565980:ios:574b98425ea8d7f4809159',
    messagingSenderId: '415407565980',
    projectId: 'one-one-learn',
    storageBucket: 'one-one-learn.appspot.com',
    iosClientId: '415407565980-1r5ntulj3p5l0gut2edv3i70r517desf.apps.googleusercontent.com',
    iosBundleId: 'com.example.oneOneLearn',
  );
}
